### ISSUE TITLE
Erro de acentuação no python 2.7

### ISSUE THREAD

**Issue by alexjosesilva** [selatotal/pythonBrasilExercicios#1]
Estou executando este codigo

# - *- coding: utf-8 - *-
import os, sys

print "EXPEDIÇÃO DE DESPACHO"

e esta saindo:

EXPEDI├ç├âO DE DESPACHO

**Comment by BrunoTeixeira1996** [comment]
boas, podes mostrar com o código identado sff?

**Comment by StefanOliveira** [comment]
Bom dia amigo, qual a versão do Python que está executando?

**Comment by alexjosesilva** [comment]
bom dia!
O python 2.7

```
- *- coding: utf-8 - *-
import os, sys
print "EXPEDIÇÃO DE DESPACHO"
```

**Saída:  EXPEDI├ç├âO DE DESPACHO**

**Comment by StefanOliveira** [comment]
Bom dia Alex, imaginei, nessa versão me recordo que quando usava caracteres tinha esse problema.

Adicione uma das 3 linhas a seguir ao cabeçalho do seu código

>  # encoding: utf-8
>  # encoding: iso-8859-1
>  # encoding: win-1252

Mas lembre-se de configurar o seu editor para quando salvar ele já ficar com a codificação, também pode efetuar o upgrade da versão resolvendo assim essa "dor de cabeça".

Referências:
[joelonsoftware](http://local.joelonsoftware.com/wiki/O_M%C3%ADnimo_Absoluto_Que_Todos_os_Programadores_de_Software_Precisam,_Absolutamente,_Positivamente_de_Saber_Sobre_Unicode_e_Conjuntos_de_Caracteres_%28Sem_Desculpas!%29)
*StackOverflow
